### ISSUE TITLE
Text inputs require TAB, SPACE, and other keys

### ISSUE THREAD

**Issue by alingham** [impress/impress.js#140]
Hi,
@alingham here - so I've already brought this one up... but finally got this way towards GitHub!

So what I'm thinking is, for my Contact form for example, when people use the Space Bar, the page flips onto the next page. If they use TAB to go to the next box, once again, it switches to the next slide.

I have disabled the use of Spacebar, but wasn't ideal.
What would be good would be to have it so when a Text area, or Text input is selected, and the cursor is flashing, then this overrides any keyboard navigation controlled by impress.js.

**Comment by marlenetiare** [comment]
thanks alot for the quickly!
finally, the javascript doesn't work for me, but in the file impress.js I erased a couple lines and it worked perfectly.

```
        document.addEventListener("keydown", function ( event ) {
            if ( (event.keyCode >= 37 && event.keyCode <= 40) ) {
                event.preventDefault();
            }
        }, false);

        document.addEventListener("keyup", function ( event ) {
            if ( (event.keyCode >= 37 && event.keyCode <= 40) ) {
                switch( event.keyCode ) {
                    case 33: // pg up
                    case 37: // left
                    case 38: // up
                             api.prev();
                             break;
                    //case 9:  // tab
                    //case 32: // space 
                    case 34: // pg down
                    case 39: // right
                    case 40: // down
                             api.next();
                             break;
                }
                
                event.preventDefault();
            }
        }, false);
```

thank u so much again!

**Comment by henrikingo** [comment]
FYI, I've now implemented [a solution](https://github.com/henrikingo/impress.js/commit/b7024817395d06222aa576d357be46b1482baf54) for this in [my fork](https://github.com/henrikingo/impress.js/).

The solution is based on @bartaz comment above: key press will only cause navigation, if focus is on BODY or HTML element. The exception is the TAB key, which will always force prev() or next() to be called. A related commit was to add [blur() to be called](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/form/form.js) on each transition. This ensures that focus is not left on a form input field that is no longer on the active slide, so that user could type a lot of keys and cause garbage to be accidentally entered into the form field.

You can play with a [demo here](http://henrikingo.github.io/impress.js/examples/classic-slides/#/acme). (Press pause button on bottom right to disable autoplay.)
