### ISSUE TITLE
using SVG in an impress.js step (no smooth scaling)

### ISSUE THREAD

**Issue by toxin20** [impress/impress.js#198]
I wanted to use an big .svg file in an impress step and then zoom in to that svg in later steps. unfortunately the svg doesn't scale smoothly but gets pixelated instead. is there an workaround for that?

here is my code:

```html
<div id="whole-map" class="step" data-x="0" data-y="0" data-scale="5">
  <object data="img/spon_uebersicht.svg" width="1000" height="1000" type="image/svg+xml" >
    <embed src="img/spon_uebersicht.svg" width="1000" height="1000" type="image/svg+xml"/>
  </object>
</div>

<div id="zoom-in-1" class="step" data-x="0" data-y="0" data-scale="1"></div>
```

**Comment by bartaz** [comment]
As far as I know when using 3D transforms browser is creating rendering layers for these elements - meaning that they are no longer treated as vectors, but as raster images (handled by GPU). That's why SVG gets pixelated when zoomed in.

The example with the tree linked above uses 2D transforms only which don't have this issue.

I don't know if there is any way to prevent it in impress.js - unless we add an option to disable 3D and use 2D transforms only for such cases. But I close this for now.

**Comment by speendo** [comment]
I don't know much about the technical details of this problem, but wouldn't it be possible to add the image far away on the z-axis instead of scaling it? Zooming in would really be zooming then...


I have the same problem :+1: :)

**Comment by bartaz** [comment]
@speendo it probably depends on the layout of other steps in presentation as the visual transition may look different between zooming (on scale) and moving closer (on z axis). But it is an idea that may help.
