### ISSUE TITLE
Simple use case - working through a long document or large image

### ISSUE THREAD

**Issue by Ed-0x1b** [impress/impress.js#223]
Pardon my inexperience, just starting with HTML5 and can't get simple use case to work with impress.js.
The simple use case is to present a long configuration file - viewed from multiple slides, some with additional text & highlighting. The series of slides should display different parts of the one large config file as a static image - I have not been able to get a static image for the slides to stay put - each slide moves the displayed config file, removing the part I want to focus on from the displayed slide. The display of the config file should be done in the .html file since it is presentation specific. I want to use SVG for the main image, but png or solarized code would also work.

apologies for filing a bug, could find any other discussions

**Comment by FagnerMartinsBrack** [comment]
Hi, it's been a long time since this issue was opened and reading the description I couldn't find anything that we could do as an action on this. Unfortunately impress.js assumes HTML5/JS/CSS knowledge to be used efficiently.

As much as I would like to help, there is not enough resources in this project that make it possible to provide a satisfactory response for this issue. I will close this for triage, but anyone is free to comment in the issue at anytime if they find something interesting that is worth sharing. Thank you!
