### ISSUE TITLE
Shift + Spacebar should take back to the previous slide.

### ISSUE THREAD

**Issue by rushiagr** [impress/impress.js#248]
A nice-to-have feature.

**Comment by FagnerMartinsBrack** [comment]
Hi @rushiagr , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by rushiagr** [comment]
I was just a normal passers-by for ImpressJS project. I am not an expert in JS and won't be able to contribute to this project in any other form in the near future. Please feel free to take a decision on this issue according to your will :)

**Comment by FagnerMartinsBrack** [comment]
@rushiagr Thanks for the response!

In this specific case is there any reason for using <kbd>shift</kbd> + <kbd>space</kbd> other than "nice to have"?

"Nice to haves" usually lead into bloat due to the low usage in the wild. Also, be aware that we should respect the [Principle of the Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) so that the shortcuts do not have to be checked by the user in the documentation. To see if we are respecting good design principles we should copy the keyboard pattern from most similar tools from other technologies.

So, for example, do you have any evidence that this shortcut exists in other presentation tools or websites to justify it's inclusion? More than one popular example, if possible, will help a lot. we already [have plans to support](https://github.com/impress/impress.js/issues/446) <kbd>shift</kbd> + <kbd>tab</kbd> for consistency with the <kbd>tab</kbd> shortcut, is there any reason that justify creating a new one?

**Comment by rushiagr** [comment]
I tried google slides and LibreOffice Impress (a Powerpoint alternative), and both of them don't have this 'shift+space' shortcut.

I am used to using 'space' to go one page down on a web page in a browser, and 'shift+space' to go one page up. I think that is where the idea to submit this issue come from. I still think that if 'space' is provided for 'next slide', similarly 'shift+space' should be provided for 'previous slide' on all presentation softwares for user experience (and to honour the principle of least astonishment, as per my opinion ), though I understand I might be in minority :)

**Comment by FagnerMartinsBrack** [comment]
> if 'space' is provided for 'next slide', similarly 'shift+space' should be provided for 'previous slide' on all presentation softwares for user experience

That's definitely a very good argument in favor of this feature.

What I see is that impress.js is using web navigation standards instead of focusing only in presentation standards. I can't give an example right now, but we might in the future have a situation where two key combinations does one thing for web navigation and another thing for presentation, this can prevent us from supporting both. Maybe I am overthinking this, but it is good to keep this potential problem in mind.

Also, in the future, we might split the keyboard navigation in a separate module in order to separate the concerns, that might allow the developer to attach web or presentation navigation at will. For now it seems reasonable to be consistent for web navigation too, or at least be consistent with the keys that are already mapped.

**Comment by Pierstoval** [comment]
Actually, after testing on many browsers, <kbd>shift</kbd>+<kbd>space</kbd> have the same beahviors, so we could implement this feature as "mixin" between web and presentation standards :smile:

**Comment by henrikingo** [comment]
#706 fixed this
