### ISSUE TITLE
How to insert Mathematica CDF file into an impress.js presentation?

### ISSUE THREAD

**Issue by ywdr1987** [impress/impress.js#275]
I've tried to embed a Mathematica CDF file into my impress.js presentation using the Embed Script Method given here: http://www.wolfram.com/cdf/adopting-cdf/deploying-cdf/web-delivery.en.html. But the CDF item remains its position when switching the slide. How can I use CDF in my impress.js presentation?

**Comment by FagnerMartinsBrack** [comment]
@ywdr1987 Sorry for taking so long to respond, but can you please upload an example of a CDF file so that we can test in impress.js and check the feasibility of supporting it?

Maybe the problem is not in impress.js itself but in the way the CDF file is created. Neverthless we need an example to look into, thanks.

**Comment by henrikingo** [comment]
Hi @ywdr1987 

The link in your original issue description no longer works. Would you like to update this issue with some example I can read?

**Comment by henrikingo** [comment]
Closing due to lack of response, but feel free to reopen if this is still an issue for you and you can provide an example file with the error happening.
