### ISSUE TITLE
The ImpressJS has support to ipad, ipod, iphone and android

### ISSUE THREAD

**Issue by viniciusdsantos** [impress/impress.js#282]
Hi my friend, thanks for your help with this amazing framework, good job :)

So, I was looking inside impress.js source and I saw that the javascript code try to discover if the devices are rendering the presentation are android, ipod or iphone and then, the impress.js do not run the presentation. But, I tested and I proved that all newest version of safari, chrome on ipod, iphone and android  are capable to support CSS3 transition and animation and transforms, so, I think you can remove this following test:
 ( ua.search(/(iphone)|(ipod)|(android)/) == -1 );

And insert the code to test if is IE or another browser/environment.
Thanks

**Comment by FagnerMartinsBrack** [comment]
Right now we can't just remove the checks unless we can be 100% sure that, for several versions of those devices, 3D transforms have been working and if it breaks, we will know it before someones reports it.

We need automated tests to be able to check if the presentations are glitchy or not. Until we have that, we should keep the browser sniffing as is. The plan is to support only the latest browsers, but [even the latest browsers can break](https://github.com/impress/impress.js/issues/443), therefore an automated test is a strong requirement to fix this problem.

**Comment by FagnerMartinsBrack** [comment]
See #273.

**Comment by deepu105** [comment]
But it would be good to have some way to disable the check  problematically, coz say if I have a presentation intended for some devices only which I know works I should be able to disable the check as I do not care of failing browsers for that presentation

**Comment by FagnerMartinsBrack** [comment]
@deepu105 For now the responsibility of telling which browser is supported and which one is not is from impress.js. In the future, if we choose to move this responsibility to the developer, then we could create something like that.

**Comment by Pierstoval** [comment]
I'm digging up this repository because I've updated [OrbitaleEasyImpress](https://github.com/Orbitale/EasyImpress) with latest impress.js version, and it seems that mobile support is still not activated because of this line:

```js
    var impressSupported =

                          // Browser should support CSS 3D transtorms
                           ( pfx( "perspective" ) !== null ) &&

                          // Browser should support `classList` and `dataset` APIs
                           ( body.classList ) &&
                           ( body.dataset ) &&

                          // But some mobile devices need to be blacklisted,
                          // because their CSS 3D support or hardware is not
                          // good enough to run impress.js properly, sorry...
                           ( ua.search( /(iphone)|(ipod)|(android)/ ) === -1 ); // <======== This line
```

I've put online the new demo of EasyImpress [here](http://demo.orbitale.io/easy_impress), and indeed the only solution to make touch work is to manually add buttons for next/previous actions.
But still, I think we could add a specific case: if "touch" is activated (whether it can be mobile or tablet or even tablet pc like HP Surface or something), we could add new events to detect left or right swiping in order to trigger next and previous events in Impress.js.

But I don't know how the "touch" API works in JS, so if you have ideas 😉

**Comment by FagnerMartinsBrack** [comment]
@Pierstoval, @and3rson have made a good progress on https://github.com/impress/impress.js/pull/496

**Comment by henrikingo** [comment]
@pierstoval: I have done exactly that in [my fork](https://github.com/henrikingo/impress.js). Feel free to use it / contribute to it while we wait for upstream to catch up.

 (Note that official impress.js also has touch support. Not swipe, but you can touch on the left or right edge to navigate. You just never see it because it refuses to load in any phone or tablet.)

**Comment by Pierstoval** [comment]
@henrikingo did you make a PR for this?

**Comment by bartaz** [comment]
Impress.js has very basic touch support (as mentioned before touch on sides of screen) that currently works on iPad only, as all others are disabled.

I've written many times about the reasons why mobile was not supported at the time impress was created, but truth is that it was years ago and things improved both in iOS and Android. Still, there may be some older devices that would simply not handle some impress presentations and using too much memory may simply crash whole Safari on iOS. So it's still safer not to enable it by default. That said, I agree that in 2016 it could (should?) be revisited and be somehow turned into option, so devs willing to take the risk of killing user browsers on mobile could turn it on.

**Comment by Pierstoval** [comment]
What were the memory issues you had? Was it about the 3d positionning, or the animations themselves?

**Comment by bartaz** [comment]
3d positioning. Each element positioned in 3d creates new rendering layer for GPU. This is every slide in impress. Safari on iOS is simply killed when memory is exceeded which may happen quite quickly on older devices (demo of impress was too much for iPhones at a time).

Of course today devices have more memory and power then couple of years ago, but you can still easily exceed it by having dozens of image heavy slides. And from impress.js user perspective you never know if your presentation will not be to heavy for some device. There is no way to detect or prevent it.

Still, this could easily be an option to enable impress on mobile 'on your own risk'. Or even programmatically set your own check for who you want to enable it instead of hard coded default one.

**Comment by Pierstoval** [comment]
Maybe could check how [Reveal.js](https://github.com/hakimel/reveal.js/) handles this? It also uses 3d positionning 😕

**Comment by bartaz** [comment]
Reveal.js only shows current plus next and previous slides. Rest is display none.

It's possible with impress if you write your CSS right, but you loose some possibilities (having all slides visible in 3d during transitions, transitioning betweetwen slides out of order etc).

**Comment by FagnerMartinsBrack** [comment]
I don't think there's much impress can do by itself. The developer is the only one that can know if their requirements allow hiding steps, what we could do is understand the limitation and document it so that it doesn't [leak](http://www.joelonsoftware.com/articles/LeakyAbstractions.html) to the user [unexpectedly](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

**Comment by henrikingo** [comment]
> @henrikingo did you make a PR for this?

It's complicated, but in short, yes, I submitted a PR for my very first changes (the qunit test framework), but it didn't end well, so I gave up on doing PRs. (I was myself part of impress.js maintainers too at that time.) My fork remains compatible with upstream impress.js (meaning, if you want to merge all 80+ additional commits together, you can), and I'm fully supportive of upstream impress.js catching up one day.

Other than that, I really don't want this thread to drift into a (potentially heated) off topic discussion, so if you have further questions about my repo, feel free to [open a separate issue for that](https://github.com/henrikingo/impress.js/issues).

On the topic itself: There is also [a patch](https://github.com/impress/impress.js/issues/333) which allows presentation authors to easily hide all slides except the current, previous and next, specifically to save RAM on small devices. [I've added that functionality](https://github.com/henrikingo/impress.js/commit/b36f518dfc192ede4b040285c9c96505955fc5bf) to my fork as well.

**Comment by Pierstoval** [comment]
Maybe there's a way to do like in video games : get all steps in memory, and on each slide, redraw the whole thing but keep only elements that are located in "extended" viewport size (meaning width+height+depth, each multiplied by 2 for example), this would allow the user and/or the developer to manually specify the "visible depth" as in video games when you want to specify the depth of rendering distant objects.

Do you think this is possible to do this at runtime? This would save a LOT of memory, actually, even for small projects. 

There would be only some drawbacks depending on the presentation itself, for example the [overview in the demo app](http://impress.github.io/impress.js/#/overview) may not show some of the elements.

Or maybe use canvas ? 😆

**Comment by henrikingo** [comment]
impress.js 1.0.0-beta1 now works (or at least tries to run) on any device.
