### ISSUE TITLE
Mobile Browser Crashing due to Memory Limit

### ISSUE THREAD

**Issue by KZeni** [impress/impress.js#333]
I created a presentation that ended up crashing mobile browsers 100% of the time (be it Mobile Safari/Chrome, iPhone/iPad, etc.) This seems linked to a memory limit when looking in the crash logs. Now, this is rather tied to the complexity of the presentation itself, but I'm thinking Impress.JS can/should have an option to enable a "Mobile-optimized" version of the presentation playback that makes it so the memory limit isn't exceeded on mobile devices. This makes it so the ideal presentation can be made for desktop, but it can still be viewed (at least doesn't crash) on mobile.

I have an actual fix to this memory limit crash. It effectively detects mobile browsers, and hides all slides except for the current, next, and previous when viewed on a mobile device. Here's a link to a gist of the code snippet that's simply added to the &lt;head&gt; of the presentation's HTML: https://gist.github.com/KZeni/6735287

Now, this is a fix that's added to a presentation that's already built out, but I'm wondering if Impress can actually have an option that enables a mode that does this for mobile devices without any added code (aside from enabling the option). Also, I don't recommend this being the default behavior as presentations that don't crash on mobile might as well continue to show all slides.

---

Edit @FagnerMartinsBrack, [see below](https://github.com/impress/impress.js/issues/333#issuecomment-204729226):
- [ ] Create an issue or PR to update the README so that browser support is clear.
- [ ] Create an issue to discuss if the memory footprint should be handled in impress.js or in the userland.

**Comment by FagnerMartinsBrack** [comment]
@bilus @KZeni 

> I'm sorry to hear that it have given you a headache on launch day, but impress.js README has quite a large and detailed section about browser support

...

> I honestly don't think it's sufficiently explained in the Readme

I am not sure if the README is still in the same state as at the time this issue was created. But I guess the best action here would be to review the README so that it is clearer on what the project supports and what it does not.

Currently [we have](https://github.com/impress/impress.js/tree/8e4888385355059d60b608a19245bd300752bb86#impressjs):

> but some tablets are good enough to run it, so it should work quite well on iPad (iOS 5, or iOS 4 with HTML5 polyfills) and Blackberry Playbook. Inform us of any bug and we will try to fix this.

and in another point of the README:

> Mobile browsers are currently not supported.

It is not clear what "mobile" means here, if it is just smartphones or it also includes tablets (it doesn't seems so).

We need to remove this subjective interpretation from the README.

Actions from this issue:

* Create an issue or PR to update the README so that browser support is clear.
* Create an issue to discuss if the memory footprint should be handled in impress.js or in the userland.

If you are wondering why you are receiving a response on this after so many time, take a look [here](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) for a little bit of context.

**Comment by KZeni** [comment]
What made it weird for me was the fact that it worked fine on my iPad at the time when I had started making the presentation, but then only started crashing after a certain number of graphical elements & image resources were being shown (which I then don't want to compromise the presentation to accommodate the technical limitation). So it seemed to work until a not necessarily predictable slide/resource limit.

My code in my first commend above had made it so the presentation slides would only show the recent & upcoming slides so it could be scalable and work regardless of the size of the images and overall presentation (though the code itself wasn't necessarily the best implementation of adding performance scaling).

I'm not sure what the best way to re-write the browser support section of the README would be or know the very best way to implement the performance scaling, but I'm glad to hear it's being worked on/taken into consideration.

**Comment by FagnerMartinsBrack** [comment]
@KZeni 

This issue might take some time to be addressed, in the meantime, since you seems to be still tracking this, could you keep testing this issue in browsers and posting the results here so that we know how the state of things are changing over time?

It would also be amazing if you could attach any Chromium/Firefox/Safari issue tracker that can somehow be related to this so that we can have some context of the browsers that might be willing to fix this in their side, if any?

**Comment by henrikingo** [comment]
Hi @KZeni 

I think your idea of hiding steps that are not in the immediate vicinity of the current step is a good way to significantly reduce memory consumption on smaller mobile devices. In any case, since using this is completely optional, up to the author using css, I've added your code as [a plugin|https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/mobile] into my impress.js fork. Please have a look.

**Comment by henrikingo** [comment]
`mobile` plugin is now merged to master. Thanks @KZeni !

**Comment by CJohnDesign** [comment]
Does anyone still find this to be a problem - crashing because it's too big?

I had something like the above gist in place and it created blank pages when I started navigating around with goto()'s

I think the newer mobile browsers have the power ;)
