### ISSUE TITLE
Embed Youtube video is black only in Firefox 

### ISSUE THREAD

**Issue by xxx2201135** [impress/impress.js#342]
Hello dear Bartaz and others,

First of all I would like to thank you for the best presentation program ever made.

For second, I have the problem when I want to play embed YouTube videos in Impress.js.
In Chrome/Opera/Explorer are those videos working great, but when I start my presentation in Firefox, videos appears only as "black screen".

It is happening only in Impress.js, because on my ordinary web-site have Firefox no problems with playing the embed youtube videos.

Please, could you help me? I would very appreciate every information. 
Thank you for your answer & time. All the best.

**Comment by FagnerMartinsBrack** [comment]
@eduardrock says that using the HTML5 player it works:

> The problem is the Flash Player. I use the HTML5 Youtube player and it looks well on Impress.js

We refrain from supporting old technologies (Flash) and I guess Youtube doesn't even use Flash anymore these days, so the problem fixed itself :tada: 

Also, @bartaz commented:

> Can you provide a link where issue can be reproduced?

and received no response. Therefore closing due to the lack of feedback from the OP. Feel free to comment here to open up the discussion again if necessary.
