### ISSUE TITLE
using #id rather than #/id with history API

### ISSUE THREAD

**Issue by jacekkopecky** [impress/impress.js#345]
Hi, I just heard about impress.js the other day and I'm truly impressed. Many thanks! 8-)

impress.js uses #/id to avoid the browser scrolling to the anchor, but the recommended way of linking into the presentation is #id. I've tried using the history API as follows to remove the slashes, and it works for me, but I'm no HTML5 wizard so I don't know what limitations this might be introducing. Anyway, maybe it helps.

Patch: 

```
diff --git a/js/impress.js b/js/impress.js
index dedcefa..caa95fe 100644
--- a/js/impress.js
+++ b/js/impress.js
@@ -609,7 +609,10 @@
             // makes transtion laggy.
             // BUG: http://code.google.com/p/chromium/issues/detail?id=62820
             root.addEventListener("impress:stepenter", function (event) {
-                window.location.hash = lastHash = "#/" + event.target.id;
+                lastHash = "#" + event.target.id;
+                if (window.location.hash !== lastHash) {
+                    history.pushState(null, null, lastHash);
+                }
             }, false);

             window.addEventListener("hashchange", function () {
```

**Comment by henrikingo** [comment]
Hi Jacek

When you say 

> impress.js uses #/id to avoid the browser scrolling to the anchor, but the recommended way of linking into the presentation is #id 

What exactly do you mean by "recommended"? It seems to me having slashes in the anchor is quite common, and may indeed be used to describe "state" of more complex javascript apps, rather than just linking to an element id.

Or to put it more simply, linking to something like: http://impress.github.io/impress.js/#/step-2 works just fine, so what is the problem this issue is trying to fix?

**Comment by henrikingo** [comment]
I'm closing this due to lack of response for a month. This is purely in an effort to keep the issue queue tidy. Feel free to reopen if you have more details to contribute.
