### ISSUE TITLE
Script to facilitate positioning of slides

### ISSUE THREAD

**Issue by andreamoro1** [impress/impress.js#362]
Hi, I found it hard to prepare slides and then edit them one by one to position them on the canvas. Typical scenario: I changed the size of a title tag in  the first slide, which made it necessary to move up or down all following slides, or slides related. 

This process is somewhat simplified using existing impress.js "editors", but I found they mess up the html with un-needed tags. 

Therefore, I created a simple php script that modifies the impress.js attributes with a simple command. I was wondering if this can be shared, and if so where would be a nice place to put it. Ideally, it could be translated into a browser extension, but I don't know js enough. I would be happy to contribute if anyone started up a project. In the meanwhile I am happy to share my script. 

Here are typical usages, to give you an idea of what the script accomplishes. 
 
Examples
php impressmod.php --f input.html
   list available slides and their id, if present
php impressmod.php --f input.html --steps 3-5 --x -20 --y =200
   decrease data-x by 20 and set data-y to 200 on slides 3,4,5 of input.html 
   and overwrite the file
php impressmod.php --f input.html --output output.html --steps 2,3,8-9 --x d20 --fm
   increase the data-x gap between slides 2 and 3, 3 and 8, and 
   8 and 9 by 20. Slides 2 remains unchanged. Data-x will be set 
   wherever missing
php impressmod.php --f input.html --steps 5-2,overview,8
   process slides in the following order: 5,4,3,2,[id=overview],5,4

**Comment by FagnerMartinsBrack** [comment]
Unfortunately this is not responsibility for the impress.js project itself. It is more responsibility for an authoring tool that should make it easy to do such kind of work with an efficient interface with high affordance.

I have commented in https://github.com/impress/impress.js/issues/5#issuecomment-204863263, so that future plans of an authoring tool remember to take care of such use case. Let's focus authoring tool discussions in that issue, thanks!
