### ISSUE TITLE
step back fails if using "past" "present" and "future" for effects

### ISSUE THREAD

**Issue by jejb** [impress/impress.js#371]
The problem is the code in impress:stepexit which assumes the exited step becomes past.  If we're stepping backwards in the presentation this is untrue.  It means that going back, the next step becomes "past" not "future".  I fixed this by detecting a backward (or jump) step in impress:stepenter in this code:

http://git.kernel.org/cgit/linux/kernel/git/jejb/impress.js.git/commit/?id=a8b1626c50793567f013115c9f050fcc3edd4619

**Comment by FagnerMartinsBrack** [comment]
Hi @jejb, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again

Also, this is being close because there is not enough information and the link provided doesn't work anymore.
