### ISSUE TITLE
Can't click on overview in Chrome 27

### ISSUE THREAD

**Issue by tjwudi** [impress/impress.js#374]
And no error reported.

**Comment by FagnerMartinsBrack** [comment]
Hi @tjwudi , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again.

I just checked the overview in Chrome 49.0.2623.112 (64-bit) on Mac and everything seems to be fine.
