### ISSUE TITLE
Minor suggestion regarding the license ("MIT or GPL" vs "MIT+GPL")

### ISSUE THREAD

**Issue by SergiuFunieru** [impress/impress.js#448]
Hi,

I LOVE impress.js! It's one of my dreams coming true!

I found it while searching the alternative for Prezi, and the 3D part plus the fact that works offline were a big plus for me.

I have only one question please : I was wondering if you'd be willing to change:
"Released under the MIT and GPL (version 2 or later) Licenses."
into:
"Released under the MIT or GPL (version 2 or later) Licenses - you may chose whatever license you like".

The reason I'm asking this is because some software are made of a mixture of parts, some with MIT and some with GPL, so there is no common license for the whole project. From what I understand, impress.js is all with one license, and that license is either MIT or GPL, depending on the user's preferences.

Thank you so much for your work,
Sergiu Funieru

**Comment by FagnerMartinsBrack** [comment]
@SergiuFunieru impress.js doesnt seems to be actively maintained. If you want advanced usage of impress you may need to use [jmpress](github.com/jmpress/jmpress.js), which is a jquery plugin which does a lot of things impress doesn't.

There is also this [angular-jmpress prototype](https://github.com/web-stories/angular-jmpress) in case you are using angular. It is just a prototype of  a basic usage since I didn't find any repository containing an angular port of jmpress.js or impress.js.

Even though you didn't mentioned it, I think its worth saying that I don't think impress.js is scalable if you want more advanced features.

**Comment by bartaz** [comment]
@SergiuFunieru Thanks for the suggestion.
When we are talking about this change, I had a look into these licences and from my understanding it seems that MIT license is compatible with GPL. This would mean that impress.js can only have MIT license and it could be used in GPL software? Or is it not correct?

**Comment by SergiuFunieru** [comment]
You're welcome.

From what I understand, you can release your software with 2 different licenses, and the user choses the one he wants. Which is actually what you did. My only wish is to change the wording, like in my original post, as now it's not clear if the user can choose the license he wants or he has to use the combination of MIT + GPL.

Thank you,
Sergiu Funieru

**Comment by bartaz** [comment]
I know that it can be released with two licenses. The question is does it have to.

As far as I understand MIT license (http://en.m.wikipedia.org/wiki/MIT_License) is compatible with GPL meaning having only MIT license would be enough for people to use it in GPL software.

That's what I want to clarify, because it will simplify licensing. 

But of course I don't have anything against changing the wording to 'MIT or GPL' if both are there to stay.

**Comment by SergiuFunieru** [comment]
Yes, I understand the same. MIT license would be enough, and one license would be also much clearer.

Usually, authors use GPL as the less restrictive license, for a commercial program. If you plan to offer your program under MIT, MIT license alone would do it.

Sergiu Funieru

**Comment by mattberther** [comment]
@bartaz: I am in the same boat -- we have a legal team that LOVES MIT licenses but is far less fond of the GPL licenses. Stating the license as MIT *or* GPL and allowing us to choose which one we use would make getting it through our legal team much easier.

All that said, I agree with @SergiuFunieru -- the choice is yours to make. Thank you for considering.

**Comment by henrikingo** [comment]
Hi @bartaz 

If your intent is to:
 1. use MIT license AND 
 2. be GPLv2 compatible,
...then, yes the MIT is sufficient as MIT licensed code can be mixed into GPLv2 licensed code. Obviously, a simple MIT file is of course also much simpler.

Explanation for this is simple: The FSF is the steward on GPLv2, and while we cannot take what they say as equivalent to law, it is fair to say that their view on GPLv2 compatibility is the strictest compared to mainstream. So when the FSF says that MIT license is compatible with GPL, then we can safely assume that is the case: http://www.gnu.org/licenses/license-list.html#X11License (yes, that is the correct link, explained if you follow it and read.)

**Comment by FagnerMartinsBrack** [comment]
My suggestion is just change to MIT once and for all so we can focus in building awesome stuff. Better focus in solving problems for humans using machines instead of having more humans problems brought into machines.

**Comment by Pierstoval** [comment]
:+1: for MIT, it's fairly enough.

**Comment by bartaz** [comment]
@henrikingo Thanks for clarification. Impress.js started as MIT only and long time ago I was asked to add GPL too. At that point also jQuery was double licensed, so I took that as an example. But my understanding today is the same - MIT should be sufficient. If in any case it's not we can figure it out later.

**Comment by henrikingo** [comment]
Cool. We have first actionable decision made! Need new pull request now.

**Comment by bartaz** [comment]
@henrikingo it's already there: #511

**Comment by FagnerMartinsBrack** [comment]
Closing as from the comment above.
