### ISSUE TITLE
Allow input and textarea in the presentation

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#525]
There are some PRs that already requested this, see #105 and #237.

I don't know what is the current behavior. Maybe we could revisit this and check whether it makes sense to implement something like this in impress.js, even if it means exposing the keybindings as a plugin and delegate the responsiblility outside impress.js core.

**Comment by Pierstoval** [comment]
I agree, just need some changes in the events IMO

**Comment by FilipMestric** [comment]
I've seen a lot of WYSIWYG editors that have textarea within the slide. I'd say you only need to put .stopPropagation() on mousedown event for textarea.

**Comment by henrikingo** [comment]
Just an update on this ticket. I was hoping forms would be fully supported in 1.0.0-beta1, but it turns out they're not.

There is a `form` plugin, which does one thing: call blur() to deselect a form element when we're leaving a slide. However, it turns out it's still the case that if you for example type 'p' into a text field, you'll end up opening impressConsole :-/
