### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by henrikingo** [impress/impress.js#541]
One of the major tasks to enable new development to happen in impress.js was to introduce a plugin api. The vision of @bartaz has been stated as keeping impress.js itself as a simple core rendering library, with a plugin api to allow for extended functionality. In fact, the functionality of advancing slides with a keypress or mouse click, is itself already implemented as such a plugin.

Building from this "hint" of what a plugin api could look like, I've now implemented some plugins in a separate branch [plugin-api](https://github.com/henrikingo/impress.js/tree/plugin-api). In fact, you can implement most plugins already without any change to impress.js itself!

Please see the [src/plugins/README.md](https://github.com/henrikingo/impress.js/blob/plugin-api/src/plugins/README.md) for a description of the plugin api and comment here what you think about it. 

I've also implemented 4 simple plugins to act as examples of 4 different types of plugins that people may want to implement more of. (The README explains and links to each of them.) Note that I've also [modified](https://github.com/henrikingo/impress.js/commits/plugin-api/index.html) the [official demo](https://github.com/henrikingo/impress.js/blob/plugin-api/index.html) to use some of the new plugins. [See demo on my github.io page](http://henrikingo.github.io/impress.js/)

PS: In [another branch](https://github.com/henrikingo/impress.js) I've also added [impressConsole.js](https://github.com/regebro/impress-console) as a git submodule. This currently doesn't conform to all the rules of the proposed Plugin API, but could do so in the future. I wanted to add it just to show another cool feature possible with plugins. In this branch I also added [another demo presentation](https://github.com/henrikingo/impress.js/tree/myfork/examples/classic-slides) that uses impressConsole.js and the Relative Positioning plugin. [See demo on my github.io page](http://henrikingo.github.io/impress.js/examples/classic-slides/)

**Comment by FagnerMartinsBrack** [comment]
I find the `plugin-api` approach very useful, the problem of course is that is adds a lot of complex guidelines that should be followed because it doesn't use a strict pattern for pluggability. But in other hand it allows full backwards compatibility, which is amazing!

An important problem to take care of is that plugins should not care about the DOM, but rather consume impress.js APIs only through JavaScript. If we allow plugins to manipulate the external DOM it will be impossible to predict what will happen when several plugins are loaded together and make sure that one code does not infer in the behavior of the other. Also, it will make impress.js impossible to extend in the future, because plugins will rely heavily on impress.js internal behavior. It will become a real mess in userland.

Ideally, a plugin should be a unit-testable with an input that returns an output that can be eventually interpreted by impress.js. The responsibility of dealing with the DOM should be from impress.js only, abstracted from plugins.

What do you think?

**Comment by henrikingo** [comment]
I've merged the plugin API and continue to work at my fork, http://github.com/henrikingo/impress.js. Hopefully we will see it land in main impress.js repo in the future.

**Comment by FagnerMartinsBrack** [comment]
Why closing this? Shouldn't we discuss this or maybe create a roadmap so that everyone is able to agree on something based on the [feedback so far](https://github.com/impress/impress.js/issues)? Shouldn't we focus the efforts to provide robust documented contracts for the consumer of the project in the main repository than just fork it and do the work elsewhere?

**Comment by henrikingo** [comment]
I don't intend to elaborate on it much in public, but the short version is that I don't find your input or reviews very useful, rather they were holding back progress for weeks and months. Since nobody else commented, it was time to close this. I've had a private discussion with Bartek to verify the API matches his original intention, which of course it should too, since it is just generalizing the navigation plugin that is already in impress.js since many years.

I will continue to develop impress.js in my fork, and I hope you can pull from it as you have time. (There's already a lot there.) But I won't do PRs or reviews any longer.

**Comment by FagnerMartinsBrack** [comment]
As developers, we have the responsibility of delivering quality software, mostly when we are putting our faces in public working for Open Source, and there are principles and patterns that helps us to achieve that. One might choose to follow or ignore those principles, but when there are too many disagreements a mechanism should be put in place, maybe in the form of a **code of conduct**, so that a common ground can be followed and goals can be made clear without hurting the success of the project, which is the end goal agreed by everyone.

It is easy to say a review is not useful without pointing out the argument and the reason why. Most of my reviews were objective and pointed out real problems, if one is uncomfortable with that I can't do much other than explain the problems that it can cause and push to the correct version. I would rather work for stability and conservative changes, than start building software without proper care.

From my point of view, what might hurt the progress of this project is the sacrifice of quality and simplicity over bloat and the urge of landing untested and unreviewed changes.

In software engineering, the best value lies on those with a [growth mindset](https://chrishildrew.files.wordpress.com/2014/03/fixedgrowth-copy.jpg), those who learn with other people inputs instead of ignoring them, even if they disagree with. I consider myself someone with that mindset, and therefore I am totally up to receive feedback in public, without fear or concern. I understand I might be wrong in many things, as everyone else, but if one is not capable of presenting a reasonable evidence that something is wrong, then it will be impossible to fix it or even justify it is a real problem.

@henrikingo, I found most of your contributions so far very useful, it drove interesting conversation and the beginning of documenting standard practices for the success of impress.js. It is very unfortunate that you don't want to contribute to the project because you don't feel comfortable with my reviews. The only thing I can suggest, as a contributor and someone who cares deeply about impress.js [since many years ago](https://github.com/impress/impress.js/issues/435), is to understand which principles we disagree with, and build a **code of conduct** that discusses those issues and documents what was agreed in consensus, so that the project can move forward.

For the good health of the project and in respect to the ones who are watching this, I will definitely not talk with somebody else in private about discussions that should be open source. If the opinion that I am not helping the project or providing useful reviews is also shared by @bartaz, and nobody want to take any action on solving this though dialog, then I will gladly step out and let somebody else takeover.

Otherwise, if you really care about impress.js, feel free to accept my suggestion to discuss a **code of conduct** and get this solved instead of focusing the efforts in building a fork of the project for one your specific use case.

I hope you consider, and I'm sorry if any of my reviews were not useful for you.

**Comment by vorpalvorpal** [comment]
I'm a bit lost wading through the issues and pull requests for impress.js. Is a plugin architecture for impress going ahead, and if it is, is it based on the work in [henrikingo's repo](https://github.com/henrikingo/impress.js)?

**Comment by henrikingo** [comment]
Hi @vorpalvorpal 

I'm happy to tell you, that we're currently working on merging my work into the dev branch of impress.js repo. (This is mostly just to allow Bartek and Fagner to read up on it, the repos themselves are not diverged, so there's not a lot of actual merging work.) Once done, the dev branch will be merged into master. I estimate a couple a months until that actually happens. Please continue to use my repo until then.

**Comment by vorpalvorpal** [comment]
Thanks. Good to hear.
