### ISSUE TITLE
Feature Request: Steps inside Steps/Slides (progressively shwoing something without changing camera position)

### ISSUE THREAD

**Issue by Chrisstar56** [impress/impress.js#600]
Could you add a feature that you progressively show steps without changing camera position. This could be useful for showing lists or similar things. If this already is possible, then I'm sorry opening the issue.

**Comment by emilioferrucci** [comment]
I need this too! Is there a better way than just copying the divs and adding html for each bullet point (e.g. like [this](http://jsfiddle.net/GCn8j/207/))?

**Comment by rethna2** [comment]
I have developed a small module for this purpose. Please refer https://github.com/rethna2/microsteps. Let me know if it helps.

**Comment by patricebeutler** [comment]
I forked and modified impress to include substeps. I also changed the documentation and the demo. See: https://github.com/patricebeutler/impress.js

**Comment by henrikingo** [comment]
Hi all

Since this is a popular feature request, I have [implemented substeps in my fork of impress.js today](https://github.com/henrikingo/impress.js/commit/674ce0a4dae9cb58acd4c1013fcf061fcbff818c).

* [Demo](http://henrikingo.github.io/impress.js/examples/classic-slides/#/step-9)
* [README](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/substep)

I also want to note that I was aware of the many other implementations of this feature request, but since my fork of impress.js uses [a plugin framework](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/README.md) to add new features, none of them could have been used as such.

Perhaps the major functional difference in what I ended up doing is that the plugin only sets/unsets a CSS class `substep-visible`, and the act of showing or hiding a substep is left to the author of the presentation by way of using CSS. (Same philosophy is already used in some other plugins, such as [mouse-timeout](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/mouse-timeout).)

**Comment by frederikmoellers** [comment]
You can also use a JavaScript snippet like [this](https://github.com/frederikmoellers/hovercraft-template/blob/master/js/oneatatime.js) and then use the `oneatatime` CSS class on the `step` `div`s. It will take care of the rest.
The snippet was originally developed for [hovercraft](https://github.com/regebro/hovercraft), but it should be usable in "regular" impress.js as well. Maybe you need to add support for pressing the space bar, but that should be it.

**Comment by henrikingo** [comment]
substep plugin is now merged into master.
