### ISSUE TITLE
Loading the library in a SPA

### ISSUE THREAD

**Issue by gazpachu** [impress/impress.js#603]
At the moment, there's no way of destroying the impress instance and all its events, therefore we get errors like this one:

```
Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLDocument.<anonymous> (impress.js:788)
```

And this is the section in `impress.js` that fails:

```
// Delegated handler for clicking on step elements
        document.addEventListener( "click", function( event ) {
            var target = event.target;

            // Find closest step element that is not active
            while ( !( target.classList.contains( "step" ) &&
                      !target.classList.contains( "active" ) ) &&
                      ( target !== document.documentElement ) ) {
                target = target.parentNode;
            }

            if ( api.goto( target ) ) {
                event.preventDefault();
            }
        }, false );
```

**Comment by gazpachu** [comment]
I think this has something to do with the fact that impressJS click events are attached to everything in the DOM. We should make the events attached only to the `root` element defined in the `init` method.

Same thing for the classes added to the `body`. They should be added to the `root` element.

**Comment by FagnerMartinsBrack** [comment]
@gazpachu I'm not, feel free to go for it and create a PR. Just try to be as simple and focused as possible and add tests to prevent regression.

[Without this first](https://github.com/impress/impress.js/issues/575) it's very hard to make changes in the framework, and that's what is holding us for now, but nothing prevents you from trying to tackle down all the events and creating a `destroy` functionality with tests. After all, it's a feature proposal that was already been accepted.

I can move it to the next minor version if everything goes fine.

**Comment by gazpachu** [comment]
@FagnerMartinsBrack Ok. Any suggestions regarding the testing part?

**Comment by FagnerMartinsBrack** [comment]
@gazpachu Which kind of suggestion? It might be possible to use the [existing test structure](https://github.com/impress/impress.js/tree/82bc45e6b002a6bb02b032f6bf2405b6e4769ff1/test) to initialize impress.js and create a test that destroys it. After destroying we can assert against every element or event that should have been removed according to our knowledge of what the framework changes in the page.

In this case, we can make the [tests drive the implementation](https://medium.com/@fagnerbrack/why-test-driven-development-4fb92d56487c) so that we make sure the functionality is 100% covered.

**Comment by henrikingo** [comment]
Hi

I hadn't announced this anywhere yet, but in the spirit of sharing, I just want to mention that I have actually implemented this kind of teardown functionality in November. (It was one of two outstanding feature requests I hadn't done earlier.) The work is done in my fork in a series of commits [starting with this one](https://github.com/henrikingo/impress.js/commit/d3e79212342b0d2b219237024b66cd759fa9de34). (Mechanism for cleaning up changed attributes is still kind of ugly, but I was able to finish a first working version.) Code structure in my repo is different from upstream impress.js, but the general idea would work and can be copied.

As you can see, the functionality is definitively non-trivial, and I would agree with @FagnerMartinsBrack it should not be attempted without having sufficient test coverage first. (Not just testing this new feature, but good coverage in general.) In my private fork I've taken the liberty of making a leap with new features while leaving creation of more tests for the future. (I have more tests than there's in upstream, but most new features don't yet have any.)

I would also argue it is too much new code to add within the current single file that is impress.js.

**Comment by FagnerMartinsBrack** [comment]
> I would also argue it is too much new code to add within the current single file that is impress.js.

I had a fork a couple of years ago where I started [splitting the files](https://github.com/web-stories/impress.js/tree/4976b8e07cc6395fb5c85676c01e4f1352b21488/src) with Grunt. Probably there's a better and cleaner way to do it because in my experience Grunt can become messy after some time.

Anyway, I guess we're going too off topic here and a dedicated issue for this would be better 😆

**Comment by henrikingo** [comment]
`impress().tear()` is now supported in 1.0.0-beta1.
