### ISSUE TITLE
Impress.js not working in ios12 on ipad

### ISSUE THREAD

**Issue by Elisenda84** [impress/impress.js#715]
Hello, 
I have created a project with impress js and I am not able to make it work on ipad air with ios 12.1.1. It works on pc, mac and android, and even on an earlier ios version (ios 10), but not on the latest 12.1.1. It throws an error in the first or second slide, and throws me out of the presentation, even when I am debugging. I am quite desperate as this is a project I've been working on for a long time. It has a volume of around 60 slides. Any help would be greatly appreciate. Thanks so much in advance.

**Comment by abertranb** [comment]
Reviewing the error Safari and Chrome crashes processing 
https://github.com/impress/impress.js/blob/master/js/impress.js#L548

Thanks!

**Comment by henrikingo** [comment]
Hi @Elisenda84 

Does the error happen only with your presentation? Can you view, for example, [the impress.js demo](https://impress.js.org/#/bored) just fine? If that's the case, then maybe it could help if you can share your presentation somewhere. Otherwise there isn't much anyone else can do for you.

Also, can you describe the error a bit more? Is it just the case that your browser exits? If yes, it's quite possible you have simply ran out of memory on the ipad. Maybe the other devices you have tested had more memory. If that is the case, then you could try to add this CSS to make your presentation a bit lighter: https://github.com/impress/impress.js/tree/master/src/plugins/mobile#example-css

**Comment by henrikingo** [comment]
Hi @abertranb 

Is your error the same as Elisenda84 is reporting?

**Comment by abertranb** [comment]
Yes @henrikingo is the same error, thanks for your reply.

**Comment by Elisenda84** [comment]
Hello @henrikingo , thanks so much for your reply, your proposal really improved the situation. Now I am able to see the presentation without being kicked out from it. I have some other problems though, as at some points it blinks and there's one slide where it gets stucked, but I am able to debug now. Thanks so much!
