### ISSUE TITLE
Change global background color

### ISSUE THREAD

**Issue by Mvrlex** [impress/impress.js#745]
I'm currently working on my first presentation with impress (really like it btw, HTML is best). I was inspired by [this](https://github.com/mkacz91/Triangulations) presentation. Which introduced a rather hacky way of changing the global (`documenty.body`) `background-color`. I needed this functionality so I wrote a little plugin for it.
It looks for a `data-background` attribute on the slide it is changing to and applies a class of that name to the `document.body`.

Is this something that could be needed by others?
If so I would love to create my first pull-request :D

**Comment by henrikingo** [comment]
Hi

I think the recommended or typical way to change background color is to set it in your CSS. Example: https://github.com/impress/impress.js/blob/master/css/impress-demo.css#L88

Note that this should already be quite powerful. For example, if you want to change the color for a particular slide:

    body.impress-on-step-1 { background: green; }

There shouldn't be a need to use Javascript for styling, plugin or otherwise. (Unless we're talking about really advanced effects and they do something else than just react to stepping to the next slide.)

That's a really nice presentation btw!

**Comment by Mvrlex** [comment]
Ok I didn't know there were classes applied to the body based on the current slide. Still one would have to set the background for every single slide, so I prefer my method. But yeah, it's not neccessary.

**Comment by henrikingo** [comment]
For sure we could improve the documentation. There's a lot of good stuff like that in impress.js that I only learned once I worked on the code itself.

Also what would be helpful for this and other use cases would be if you could group steps into sections. For your use case it would mean you wouldn't need to write css for each individual slide, but could instead do something like `body.impress-on-section-1`. (Someone wanted the table-of-contents select menu to use sections too. So it would be a generally useful concept.)
