### ISSUE TITLE
Viability of Electron Packaging ?

### ISSUE THREAD

**Issue by carywreams** [impress/impress.js#785]
Is it viable to package impressjs with Electron to become a DISPLAY app ?

or, ...

Can I  replace powerpoint with an impressjs electron app ?

We provide stock powerpoint presentations that are customized by our clients.
I'd lke to package all the assets into an electron app. Customizations would then be accomplished by loading a configuration file downloaded from our portal.

Thoughts ?

[also posted to impressionist-presentations](https://groups.google.com/g/impressionist-presentations/c/Sydcy9BdNVs)

**Comment by henrikingo** [comment]
Hi. Sorry for delay, I've had a lot of outdoor work now that the snow is gone and spring is coming :-)

Yes, this should be totally feasible. As you notice, in https://github.com/henrikingo/impressionist I have essentially done just that. It loads an impressjs presentation as the primary window in electron, and then I added a lot of stuff to make it editable, which you would ignore if you just want to show presentations.

That said, why would you rather give your customers an app to install rather than show the presentation in the browser? It seems to me opening a html file in a browser is much simpler to play anywhere?

**Comment by carywreams** [comment]
No worries. Thanks for the response.

One requirement we have is the ability to provide the presentation without benefit of internet access. Some of our clients' will not be permitted to access on-site wifi at their client's location.  That means all the assets we'd require must be available locally. Rather than ask our clients to manage that, I'd like to just package everything for them and feed the "app" a custom json config file that will drive the presentation.

Today, we provide a ppt that they customize according to their client make-up. We want to move the customization to our portal in order to generate the configuration file for the app to consume.

Sounds like I might be able to fork your repo, etxract (or not...) the editing capabilities and add our assets and core presentation.
...provided the license permits commercial usage...

Does that make sense to you ?

Thanks

**Comment by henrikingo** [comment]
It does make sense. Note that impressionist is rather old, sou you may want to copy the idea but start from scratch with the latest version of electron.

I frequently have a presentation copy locally too. Back in the day I learned to never assume that wifi at a conference center would actually work. In fact, it was a major reason to choose impress.js that it doesn't require, for example, to store presentations in some online service.

Perhaps the main drawback is just that a presentation isn't one file but many files. I've often thought it would be better to copy and send presentations as a single file, such as https://en.wikipedia.org/wiki/MHTML. But those single file formats never seemed to work well when I looked at them.

**Comment by carywreams** [comment]
Appreciate the neuro-cycles. Will circle back when I'm closer making this real. Thanks again.
