### ISSUE TITLE
Firefox v95 and Safari v15 not supported

### ISSUE THREAD

**Issue by tillmanjex** [impress/impress.js#797]
Using: 
impress v1.1.0
Safari 15.1 
Firefox 95.02 
Mac OS 12.0.1
VS Code 1.63 with Live Server 5.6.1

I get the error message on startup:
Your browser doesn't support the features required by impress.js, so you are presented with a simplified version of this presentation. 
For the best experience please use the latest Chrome, Safari or Firefox browser.

Both browsers are the latest versions. 

Don't want to download Chrome unless I have to...

**Comment by henrikingo** [comment]
Do I understand correctly, that you tried two browsers (recent versions) and neither of them worked? Usually this happens because due to some JavaScript bug impress.js simply fails to load. This can even happen if you have some mistake in your HTML code (but generally shouldn't).

For example in Firefox, could you check *Menu > More Tools > Web developer tools*. In the normal case, the console should be completely clear. If there's an error - and you don't recognize it as a problem with your presentation - then please copy the error here and I'll have a look.

**Comment by Till1001** [comment]
Ah yes.
This is what I get (I'm just using the 2D-Navigation example and have not changed anything):

![Screenshot 2021-12-27 at 10 28 36](https://user-images.githubusercontent.com/83029642/147457475-d620d5b0-00ad-4afb-8093-c0781116aaa1.png)

**Comment by henrikingo** [comment]
Ah, I see. The issue is that your browser is blocking impress.js from loading at all. localhost/127.0.0.1 has special protections for JavaScript usage. They are a bit different for each browser too, so off the top of my head I don't remember the details for each. Short version is just that this will not work.

If it's possible for you to just open the impress presentation locally, meaning as a file:/// URL, then that should work. Alternatively, try giving your localhost server some real looking domain name in your /etc/hosts file. This *may* trick the browser to think it's not running on localhost. Finally, some browsers may allow to change security settings so that it doesn't block javascript from localhost.
