### ISSUE TITLE
Authoring API

### ISSUE THREAD

**Issue by bartaz** [impress/impress.js#88]
Just to fork the discussion about API in #9 this issue is about providing additional 'extended' API with functions useful for authoring tools to build impress.js presentations.

For sure there is a need to manipulate the position of the 'camera' (transform of the canvas), ability to change the position, scale and rotation of steps, maybe dynamically adding steps, etc...

Please comment if you have any suggestions. Feedback from anyone already trying to build an authoring tools is more than welcome :)

**Comment by henrikingo** [comment]
I think my people on this thread should check out my work-in-progress [Impressionist](https://github.com/henrikingo/impressionist) 3D editor for impress.js.

A couple of things that are now in impress.js core were added to enable creating an editor: initAllSteps() is now called inside each goto(), so that dynamic changes to the presentation (add new slide) are taken into account when you call goto(). Also the new tear() method - to "uninitialize" impress back to original state - I added for Impressionist, although others had asked for that as well.

Other than that, all the editing/authoring functionality is in Impressionist itself. For example it was a lot of fun to implement a camera functionality as is also discussed here. impress.js is used to render the presentation, and impressionist adds its own functionality on top. But for the most part these remain separate and independent, and there was no need for a particular "Authoring API" in impress.js itself.

PS: I intend to move impressionist into the impress project too, once I finish cleaning up the state of impress.js first. (Which is still expected to take weeks.)
