### ISSUE TITLE
Ability to export in PDF [plain, but solid]

### ISSUE THREAD

**Issue by shamansir** [impress/impress.js#99]
Most HTML5-engines for presentations now support exporting to PDF (to share at slideshare or a similar sites), I'd like to have one here too. I don't know the real importance of it, you decide).

At least, it'd be cool to have the easy-to-share single file with pages, images and stuff included inside.

<sub>....Or, it'd be cool to have a hosting to share not only PDF, but also HTML5 Presentations....</sub>

**Comment by nootanghimire** [comment]
Use case: I always use impress.js for presenting project progress/report in my university. Most of the times, we just need to present them, so all we need is browser. But sometimes, faculty instructs us to print 'em. The situation is: I've the presentation ready in impress.js, I want to print it. Being able to convert to pdf seems to be correct solution.

I'm currently looking forward to use deck2pdf for now; i don't yet know how it works, but I think it's kinda cool for impress to have it's own "Print/Save as pdf" feature.

**Comment by jbonlinea** [comment]
HI there, 

I discovered impress.js looking for an alternative to powerpoint and prezi. 
I haven't used it yet but I totally defend the cause advanced here ; 
It's actually critical in some use case: 

Next week I'll give a talk, I don't know if I'll be able to plug my computer, if will have to use to one of the conference room, and even if the conference has a computer or a techy-techy costy-costy conference system with pointer and the forth.
I can't afford to have my whole presentation down ; having a PDF backup is mandatory.

**Comment by henrikingo** [comment]
To summarize current status:

* Is there something wrong with deck2pdf?
* impress.js presentations, in the general sense, are not "slides", rather 3D animations. The idea of printing arbitrary impress.js presentations on paper or a PDF file doesn't make sense. But it is of course possible that your particular presentation can be converted to pages on paper.
* As for @jbonlinea, I don't quite see your problem. I speak at conferences a lot, and when I used PowerPoint and OpenOffice, it was definitively necessary to have a PDF. In fact that wasn't a backup, I always used only PDF to avoid font and positioning problems. But this is 2017 and impress.js works in firefox and chrome (and probably IE and Safari?) since many years ago. Why don't you just send a zip file and tell them to unzip and open in a browser? You are much more likely to run into trouble if converting to PDF.
* As Bartek says above, it's completely possible that you don't call impress().init() and print the presentation without the 3D positioning. You can add any CSS you want for this use case, use the body.impress-not-supported selector for this mode.
* We now have plugins in impress.js. (In dev branch, but it's ready to merge.) Even if PDF export isn't meaningful to everyone, I don't mind if someone wants to create a plugin that does that. Users can then use the plugin or ignore it, it's just another file.

**Comment by jbonlinea** [comment]
HI @henrikingo 

Thank's for your detailed reply

I understand your point, indeed impress.js is not "only" about slides, and most broswer support JavaScript today.

Yet, you never know what you may bump into.
For instance you built your impress.js document in a way that it shouldn't be navigated step by step, but using links you create inside, and to do so you need a mouse (to click on the links). If your conference room only provide you a remote with left-right, you're screwed, but if you created a pdf and re-ordered you slide.


Actually, I would like to create a impress.js document that reads step 1, 2, 3, 7, 8, 13, 14 when I navigate with the keyboard arrow, but I want to have in stock the slide 4-6 and 9-12 in order to aswer some questions that are most supposed to come up, and have it within my presentation to keep the added value of understanding to have the slides, where they shouls be and not at then end of the presentation.
Actually I beleve i found and plugg-in but unfortunatly can't find it anymore ?!

**Comment by henrikingo** [comment]
Node.js will never be required to use impress.js. (It is required for development and testing.) We now place large external libraries (Markdown.js, Highlight.js, Mathjax.js and Mermaid.js) under extras/ as a git module. In other words, they are optional modules. A PDF library would probably go there as well.

**Comment by jbonlinea** [comment]
Deck2pdf install guideline suggest to use NPM, and in order to install npm on my mac, I have followed a tutorial suggesting tu use brewery to handle dependencies, and the later installed node.js as a dependency of NPM... then I was able to install and use deck2pdf !

impress.js is awesome, and having an new library to export steps in a pdf would be great !!

thank's anyhow for this great work !
